// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtywAnLqneNxbo-jrbqKU8uH2POQT83DU',
    appId: '1:45277110132:web:1e976a623b1c1911329621',
    messagingSenderId: '45277110132',
    projectId: 'noteappprovider',
    authDomain: 'noteappprovider.firebaseapp.com',
    storageBucket: 'noteappprovider.firebasestorage.app',
    measurementId: 'G-CXKBVD94ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRM0Zxx2TLi02199gVY24U8_1dcjXj9Mw',
    appId: '1:45277110132:android:251caf117ffda9aa329621',
    messagingSenderId: '45277110132',
    projectId: 'noteappprovider',
    storageBucket: 'noteappprovider.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtywAnLqneNxbo-jrbqKU8uH2POQT83DU',
    appId: '1:45277110132:web:ac64324f87f42b89329621',
    messagingSenderId: '45277110132',
    projectId: 'noteappprovider',
    authDomain: 'noteappprovider.firebaseapp.com',
    storageBucket: 'noteappprovider.firebasestorage.app',
    measurementId: 'G-TXT2YR82HQ',
  );
}
